/**
 * The declarative Convex-to-Postgres table mapping for P2-39b.
 *
 * This is the single source of truth: `ddl.ts` generates the `kith` schema
 * migration from it, and `transform.ts` maps Convex export rows to COPY-ready
 * rows from the same list, so the DDL and the transform cannot drift (the
 * row's own acceptance requirement).
 *
 * Design, see docs/plans/2026-09-12-postgres-consolidation.md section 1.2 and
 * 2.2 for the decisions this file encodes mechanically:
 *
 * - Every row's Convex `_id` becomes the Postgres primary key `id`, verbatim
 *   (2.2), typed to `@repo/kith-store`'s `kith.kith_id` domain rather than a
 *   bare `text` (see `ddl.ts`). `_creationTime` becomes `created_at
 *   timestamptz`.
 * - A space-scoped table also carries `space_id kith.kith_id` and a
 *   `UNIQUE (id, space_id)`, and every reference to another space-scoped
 *   table is a composite foreign key `(col, space_id) REFERENCES
 *   target(id, space_id)` so a cross-space reference is unrepresentable.
 * - Every `v.id("X")` field becomes its own typed `kith.kith_id` reference
 *   column (never jsonb), so the provenance-chain and space-isolation
 *   parity checks can walk and verify real foreign keys.
 * - Every scalar field (string, number, boolean, or a literal/union of
 *   literals) becomes its own nullable typed column.
 * - Every array or nested-object field becomes a `jsonb` column, unless the
 *   plan names a child table for it. The only such case today is
 *   `apiKeys.spaceIds` / `apiKeys.sourceAccountIds` (1.2), which become the
 *   `kith.api_key_spaces` and `kith.api_key_source_accounts` join tables.
 * - `thoughts.embedding` is the one field the plan (5.1) says to drop
 *   rather than store: it is declared in `excludedFields` so the transform's
 *   unmapped-field check treats it as a deliberate exclusion, not a bug.
 *
 * Five names (`spaces`, `apiKeys`, `documents`, `sourceRevisions`, `chunks`)
 * collide with tables `@repo/kith-store`'s own prototype migrations already
 * created for its synthetic proof harness; those tables are `uuid`-keyed and
 * actively exercised by that package's own tests, so this file's versions of
 * the same five domains land under a `brain_` pg name instead
 * (`brain_spaces`, and so on). See `ddl.ts`'s module comment for the full
 * reasoning.
 *
 * ponytail: every non-structural column is nullable in the generated DDL.
 * Convex's required/optional split, CHECK constraints, and the tsvector/
 * pgvector index columns are follow-up work for the rows that own each
 * domain (P2-39c through P2-39l); this row's job is structural fidelity and
 * the six parity checks, not the final production schema.
 */

export type ColumnKind =
  | "ref"
  | "text"
  | "number"
  | "boolean"
  | "jsonb"
  | "timestamp";

export type ColumnSpec = {
  pg: string;
  convex: string;
  kind: ColumnKind;
  /** Postgres table this ref column points to (bare name, no `kith.` prefix). */
  refTable?: string;
};

export type ChildTableSpec = {
  /** The Convex array field this child table replaces. */
  convexField: string;
  /** Postgres table name (bare, no `kith.` prefix). */
  pg: string;
  parentColumn: string;
  valueColumn: string;
  valueRefTable: string;
};

export type TableSpec = {
  convexTable: string;
  /** Postgres table name (bare, no `kith.` prefix). */
  pg: string;
  spaceScoped: boolean;
  /**
   * false: the table's DDL is created but the transform never loads rows
   * into it (drained before cutover, recreated empty, or re-embedded).
   * Section 1.2 and 5.1 name each such table's reason.
   */
  migrated: boolean;
  columns: ColumnSpec[];
  excludedFields?: string[];
  children?: ChildTableSpec[];
};

function snake(name: string): string {
  return name.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`);
}

// The three structural columns every table already carries (id, space_id,
// created_at from _creationTime). A handful of Convex tables also have their
// own domain `createdAt` field (distinct from `_creationTime`); suffixed so
// neither column is silently dropped by a duplicate-name collision.
const RESERVED_PG_NAMES = new Set(["id", "space_id", "created_at"]);

function pgName(convex: string): string {
  const base = snake(convex);
  return RESERVED_PG_NAMES.has(base) ? `${base}_field` : base;
}

function ref(convex: string, refTable: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "ref", refTable };
}
function text(convex: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "text" };
}
function num(convex: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "number" };
}
function bool(convex: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "boolean" };
}
function json(convex: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "jsonb" };
}
function ts(convex: string): ColumnSpec {
  return { pg: pgName(convex), convex, kind: "timestamp" };
}

function table(
  convexTable: string,
  pg: string,
  spaceScoped: boolean,
  migrated: boolean,
  columns: ColumnSpec[],
  opts: { excludedFields?: string[]; children?: ChildTableSpec[] } = {},
): TableSpec {
  return { convexTable, pg, spaceScoped, migrated, columns, ...opts };
}

export const TABLES: TableSpec[] = [
  // --- Auth (1.5, 1.2): only users and authAccounts migrate. The other five
  // Convex auth tables are session/verifier/rate-limit state with no target
  // in this row (authSessions becomes a new kith.sessions design in P2-39c).
  table("users", "users", false, true, [
    text("name"),
    text("email"),
    text("image"),
    ts("emailVerificationTime"),
    text("phone"),
    ts("phoneVerificationTime"),
    bool("isAnonymous"),
  ]),
  table("authAccounts", "auth_accounts", false, true, [
    ref("userId", "users"),
    text("type"),
    text("provider"),
    text("providerAccountId"),
    text("secret"),
    text("emailVerified"),
    text("phoneVerified"),
  ]),
  table("consumedOAuthCodes", "consumed_oauth_codes", false, false, [
    ref("userId", "users"),
    ref("apiKeyId", "brain_api_keys"),
    text("requestHash"),
    text("codeHash"),
    text("bindingHash"),
    text("keyHash"),
    ts("expiresAt"),
  ]),

  // --- Spaces and membership
  table("spaces", "brain_spaces", false, true, [
    text("kind"),
    text("name"),
    ref("createdBy", "users"),
  ]),
  table("spaceMembers", "space_members", true, true, [
    ref("userId", "users"),
    text("role"),
    ref("personEntityId", "entities"),
  ]),
  table("userSpaceSettings", "user_space_settings", false, true, [
    ref("userId", "users"),
    ref("personalSpaceId", "brain_spaces"),
    ref("defaultWriteSpaceId", "brain_spaces"),
  ]),
  table(
    "apiKeys",
    "brain_api_keys",
    false,
    true,
    [
      ref("userId", "users"),
      text("keyHash"),
      text("keyPrefix"),
      text("name"),
      ts("lastUsedAt"),
      json("capabilities"),
      text("oauthLifecycle"),
      text("oauthRequestHash"),
      text("oauthCodeHash"),
      text("oauthBindingHash"),
      text("oauthBindingSeedHash"),
      text("oauthEncryptedCode"),
      ts("oauthGrantExpiresAt"),
      ts("oauthPreparationExpiresAt"),
      text("oauthPreparationNonce"),
    ],
    {
      children: [
        {
          convexField: "spaceIds",
          pg: "api_key_spaces",
          parentColumn: "api_key_id",
          valueColumn: "space_id",
          valueRefTable: "brain_spaces",
        },
        {
          convexField: "sourceAccountIds",
          pg: "api_key_source_accounts",
          parentColumn: "api_key_id",
          valueColumn: "source_account_id",
          valueRefTable: "source_accounts",
        },
      ],
    },
  ),
  table("familyInvitations", "family_invitations", true, true, [
    text("emailNormalized"),
    text("tokenHash"),
    text("role"),
    text("status"),
    ref("createdBy", "users"),
    ts("createdAt"),
    ts("expiresAt"),
    ref("acceptedBy", "users"),
    ts("acceptedAt"),
    ref("approvedBy", "users"),
    ts("approvedAt"),
    ref("membershipId", "space_members"),
    ref("revokedBy", "users"),
    ts("revokedAt"),
  ]),

  // --- Source accounts and provenance
  table("sourceAccounts", "source_accounts", true, true, [
    text("connector"),
    text("accountId"),
    text("name"),
    bool("enabled"),
    text("cursor"),
    num("cursorVersion"),
    num("freshnessMs"),
    ts("coverageInvalidatedAt"),
    ts("lastEnumeratedAt"),
    ts("lastProcessedAt"),
    num("inventoryEpoch"),
    num("completedInventoryEpoch"),
    num("manifestVersion"),
    ref("activeWorkerScanId", "worker_source_scans"),
    num("workerAssessmentEpoch"),
    ref("activeWorkerAssessmentId", "worker_processing_assessments"),
    ref("latestWorkerAssessmentId", "worker_processing_assessments"),
    text("binaryProfileId"),
    json("binaryProfileIds"),
    text("binaryProfileAuditDigest"),
    ts("binaryProfileEnabledAt"),
    ref("subjectEntityId", "entities"),
    bool("embedFullChunks"),
    ref("createdBy", "users"),
  ]),
  table("sourceItems", "source_items", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("externalIdHash"),
    text("externalId"),
    text("title"),
    text("docType"),
    text("uri"),
    text("lifecycle"),
    bool("originalLinkAvailable"),
    ref("desiredRevisionId", "brain_source_revisions"),
    num("desiredProcessingEpoch"),
    ref("activeRevisionId", "brain_source_revisions"),
    ref("activeGenerationId", "processing_generations"),
    ref("activeCardGenerationId", "processing_generations"),
    bool("embedFullChunks"),
    json("lastFailure"),
    ts("forgottenAt"),
    ref("forgottenBy", "users"),
    num("archiveDeletionForgetEpoch"),
    num("archiveDeletionReceiptCount"),
    ts("archiveDeletionCompletedAt"),
    num("workerObservationEpoch"),
    num("workerProcessingEpoch"),
    text("workerInventoryMetadataDigest"),
    text("workerProcessingIdentityDigest"),
    text("workerContentHash"),
    ts("workerSourceModifiedAt"),
    text("workerProfileId"),
    num("workerLastSeenInventoryEpoch"),
  ]),
  table("sourceRevisions", "brain_source_revisions", true, true, [
    ref("sourceItemId", "source_items"),
    text("contentHash"),
    num("byteLength"),
    text("mediaType"),
    text("representation"),
    text("contentHashAuthority"),
    text("inlineText"),
    ts("capturedAt"),
    ref("userId", "users"),
    text("archiveRef"),
  ]),
  table("sourceParserArtifacts", "source_parser_artifacts", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    text("clientArtifactId"),
    text("parserFingerprint"),
    text("outputHash"),
    num("outputByteLength"),
    text("outputMediaType"),
    text("hashAuthority"),
    ref("userId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    ts("createdAt"),
  ]),
  table(
    "sourceArtifactArchiveReceipts",
    "source_artifact_archive_receipts",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("parserArtifactId", "source_parser_artifacts"),
      text("subjectKind"),
      text("copyRole"),
      text("clientReceiptId"),
      text("requestDigest"),
      text("receiptVersion"),
      text("archiveRepresentation"),
      text("archiveProfileFingerprint"),
      text("archiveIdentityFingerprint"),
      text("recipientFingerprint"),
      text("repositoryKeyDomainFingerprint"),
      text("storageFailureDomainFingerprint"),
      text("archiveObjectId"),
      text("plaintextHash"),
      num("plaintextByteLength"),
      text("plaintextMediaType"),
      text("hashAuthority"),
      text("ciphertextHash"),
      num("ciphertextByteLength"),
      text("verificationKind"),
      ts("readbackVerifiedAt"),
      ref("userId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      ts("createdAt"),
    ],
  ),
  table(
    "sourceArtifactArchiveBindings",
    "source_artifact_archive_bindings",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("parserArtifactId", "source_parser_artifacts"),
      text("subjectKind"),
      text("subjectKey"),
      text("copyRole"),
      ref("receiptId", "source_artifact_archive_receipts"),
      text("archiveIdentityFingerprint"),
      num("bindingEpoch"),
      ts("updatedAt"),
      ref("userId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
    ],
  ),
  table(
    "sourceArtifactDeletionAcks",
    "source_artifact_deletion_acks",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("receiptId", "source_artifact_archive_receipts"),
      num("forgetEpoch"),
      text("deletionId"),
      text("requestId"),
      text("requestDigest"),
      text("ackVersion"),
      text("absenceAuthority"),
      text("retentionDisclosure"),
      text("clientReceiptId"),
      text("receiptRequestDigest"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("parserArtifactId", "source_parser_artifacts"),
      text("subjectKind"),
      text("copyRole"),
      text("receiptVersion"),
      text("archiveRepresentation"),
      text("archiveProfileFingerprint"),
      text("archiveIdentityFingerprint"),
      text("recipientFingerprint"),
      text("repositoryKeyDomainFingerprint"),
      text("storageFailureDomainFingerprint"),
      text("archiveObjectId"),
      text("plaintextHash"),
      num("plaintextByteLength"),
      text("plaintextMediaType"),
      text("hashAuthority"),
      text("ciphertextHash"),
      num("ciphertextByteLength"),
      text("verificationKind"),
      ts("readbackVerifiedAt"),
      ref("receiptUserId", "users"),
      ref("receiptActorCredentialId", "brain_api_keys"),
      ts("receiptCreatedAt"),
      text("objectOutcome"),
      text("backupOutcome"),
      ref("actorUserId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      ts("completedAt"),
    ],
  ),
  table(
    "sourceProviderOriginalReferences",
    "source_provider_original_references",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      text("clientReferenceId"),
      text("requestDigest"),
      text("referenceVersion"),
      text("providerKind"),
      text("referenceFingerprint"),
      text("sourceContentHash"),
      num("sourceByteLength"),
      text("providerAccountIdHash"),
      text("providerRootDirectoryIdHash"),
      text("providerFileIdHash"),
      text("providerRevision"),
      text("providerContentHash"),
      ts("verifiedAt"),
      text("locatorBindingId"),
      text("locatorManifestFingerprint"),
      text("locatorRecipientFingerprint"),
      text("locatorRepositoryKeyDomainFingerprint"),
      text("locatorRepositoryId"),
      text("locatorSnapshotId"),
      text("locatorObjectName"),
      text("locatorCiphertextHash"),
      num("locatorCiphertextByteLength"),
      ts("locatorReadbackVerifiedAt"),
      text("verificationAuthority"),
      ref("userId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      ts("createdAt"),
    ],
  ),
  table(
    "sourceProviderOriginalBindings",
    "source_provider_original_bindings",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("referenceId", "source_provider_original_references"),
      num("bindingEpoch"),
      ts("verifiedAt"),
      ref("userId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      ts("updatedAt"),
    ],
  ),
  table(
    "sourceProviderOriginalDetachAcks",
    "source_provider_original_detach_acks",
    true,
    true,
    [
      text("ackVersion"),
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("referenceId", "source_provider_original_references"),
      num("forgetEpoch"),
      text("detachId"),
      text("requestId"),
      text("requestDigest"),
      text("referenceFingerprint"),
      text("locatorBindingId"),
      text("locatorRepositoryId"),
      text("locatorSnapshotId"),
      text("locatorObjectName"),
      text("referenceOutcome"),
      text("locatorBundleOutcome"),
      text("locatorAbsenceAuthority"),
      text("retentionDisclosure"),
      text("providerSourceOutcome"),
      ref("actorUserId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      ts("completedAt"),
    ],
  ),
  table("sourceTextVersions", "source_text_versions", true, true, [
    ref("sourceRevisionId", "brain_source_revisions"),
    text("extractionFingerprint"),
    text("representation"),
    text("text"),
    text("textHash"),
    text("textHashAuthority"),
    num("byteLength"),
    num("utf16Length"),
    num("pageCount"),
    text("mappingManifestHash"),
    ref("parserArtifactId", "source_parser_artifacts"),
    bool("evidenceSealed"),
  ]),
  table("sourcePages", "source_pages", true, true, [
    ref("sourceTextVersionId", "source_text_versions"),
    num("ordinal"),
    num("start"),
    num("end"),
    text("text"),
    text("textHash"),
  ]),
  table("evidenceSpans", "evidence_spans", true, true, [
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    ref("sourcePageId", "source_pages"),
    num("ordinal"),
    num("start"),
    num("end"),
    text("quoteHash"),
    json("locator"),
    json("cardExtractionFingerprints"),
  ]),
  table("documents", "brain_documents", true, true, [
    ref("processingGenerationId", "processing_generations"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    text("documentKey"),
    text("title"),
    text("docType"),
    ts("capturedAt"),
    json("evidenceSpanIds"),
    text("publicationState"),
  ]),
  table("chunks", "brain_chunks", true, true, [
    ref("processingGenerationId", "processing_generations"),
    ref("documentId", "brain_documents"),
    num("ordinal"),
    ref("sourceTextVersionId", "source_text_versions"),
    num("start"),
    num("end"),
    text("text"),
    json("evidenceSpanIds"),
    text("publicationState"),
  ]),
  table("processingGenerations", "processing_generations", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    text("processingFingerprint"),
    text("extractionFingerprint"),
    text("extractorFingerprint"),
    text("recordSchemaFingerprint"),
    text("normalizationFingerprint"),
    text("chunkerFingerprint"),
    text("correctionRevision"),
    ref("parserArtifactId", "source_parser_artifacts"),
    text("archiveSetDigest"),
    text("normalizedBundleDigest"),
    ref("originalPrimaryReceiptId", "source_artifact_archive_receipts"),
    ref("originalBackupReceiptId", "source_artifact_archive_receipts"),
    ref("originalProviderReferenceId", "source_provider_original_references"),
    num("originalProviderBindingEpoch"),
    ref("parserPrimaryReceiptId", "source_artifact_archive_receipts"),
    ref("parserBackupReceiptId", "source_artifact_archive_receipts"),
    num("desiredProcessingEpoch"),
    bool("cardGeneration"),
    text("state"),
    num("expectedPageCount"),
    num("expectedEvidenceSpanCount"),
    num("expectedDocumentCount"),
    num("expectedChunkCount"),
    num("expectedEventCount"),
    num("expectedObservationCount"),
    num("actualPageCount"),
    num("actualEvidenceSpanCount"),
    num("actualDocumentCount"),
    num("actualChunkCount"),
    num("actualEventCount"),
    num("actualObservationCount"),
    ref("payloadManifestId", "processing_generation_payload_manifests"),
    text("embeddingStatus"),
    ts("activatedAt"),
    ts("deactivatedAt"),
  ]),
  table(
    "processingGenerationPayloadManifests",
    "processing_generation_payload_manifests",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("sourceTextVersionId", "source_text_versions"),
      ref("parserArtifactId", "source_parser_artifacts"),
      ref("processingGenerationId", "processing_generations"),
      text("archiveSetDigest"),
      text("normalizedBundleDigest"),
      text("mappingManifestHash"),
      json("pageIds"),
      json("evidenceSpanIds"),
      json("documentIds"),
      json("chunkIds"),
      num("pageCount"),
      num("evidenceSpanCount"),
      num("documentCount"),
      num("chunkCount"),
      num("pageBytes"),
      num("evidenceBytes"),
      num("documentBytes"),
      num("chunkBytes"),
      text("pageDigest"),
      text("evidenceDigest"),
      text("documentDigest"),
      text("chunkDigest"),
      text("retainedTextHash"),
      num("retainedTextUtf8Length"),
      num("retainedTextUtf16Length"),
      text("manifestVersion"),
      ts("createdAt"),
    ],
  ),
  table("ingestRequests", "ingest_requests", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("requestId"),
    text("requestDigest"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("processingGenerationId", "processing_generations"),
    ref("ingestJobId", "ingest_jobs"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
  ]),
  table("ingestJobs", "ingest_jobs", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("processingGenerationId", "processing_generations"),
    ref("admittedByUserId", "users"),
    ref("admittedByCredentialId", "brain_api_keys"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    ts("actorReplacedAt"),
    ref("actorReplacedBy", "users"),
    num("desiredProcessingEpoch"),
    text("state"),
    num("attempts"),
    num("leaseEpoch"),
    text("leaseToken"),
    ts("leaseExpiresAt"),
    bool("workerManaged"),
    ref("workerLeaseOwnerCredentialId", "brain_api_keys"),
    ts("nextAttemptAt"),
    json("error"),
    ref("workerDiscoveryWorkId", "worker_discovery_work"),
    num("workerObservationEpoch"),
    text("workerProcessingMode"),
  ]),
  table("inlineWork", "inline_work", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("processingGenerationId", "processing_generations"),
    ref("ingestJobId", "ingest_jobs"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    text("state"),
    num("attempts"),
    ts("nextAttemptAt"),
    text("lastErrorCode"),
    ts("createdAt"),
    ts("updatedAt"),
  ]),
  table("ingestRateLimits", "ingest_rate_limits", false, false, [
    ref("credentialId", "brain_api_keys"),
    ts("windowStartedAt"),
    num("count"),
  ]),
  table("sourceFetchRequests", "source_fetch_requests", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    text("requestId"),
    text("requestDigest"),
    text("url"),
    text("title"),
    text("state"),
    ts("createdAt"),
  ]),
  table("spaceProcessingState", "space_processing_state", true, true, [
    num("activationEpoch"),
    ts("activatedAt"),
  ]),

  // --- Events, observations and cards
  table("events", "events", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    text("eventKey"),
    ref("createdBy", "users"),
  ]),
  table("eventVersions", "event_versions", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    ref("processingGenerationId", "processing_generations"),
    ref("eventId", "events"),
    ref("entityId", "entities"),
    text("eventType"),
    num("schemaVersion"),
    json("occurrence"),
    text("occurrenceDate"),
    ts("occurrenceInstant"),
    text("occurrenceSortKey"),
    json("fieldEvidence"),
    json("docTypePatch"),
    ref("userId", "users"),
  ]),
  table("observations", "observations", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    ref("processingGenerationId", "processing_generations"),
    ref("eventId", "events"),
    ref("eventVersionId", "event_versions"),
    ref("entityId", "entities"),
    text("eventType"),
    json("occurrence"),
    text("occurrenceDate"),
    ts("occurrenceInstant"),
    text("occurrenceSortKey"),
    text("observationKey"),
    text("observationType"),
    num("schemaVersion"),
    // ponytail: money observations stay jsonb here; P2-39f (Records, cards
    // and coverage, section 6) promotes the money-shaped values to NUMERIC
    // under the finance domain, per plan section 1.2's `observations` row.
    json("value"),
    json("valueEvidence"),
    ref("boundEntityId", "entities"),
    ref("userId", "users"),
  ]),
  table("cardEntityBindings", "card_entity_bindings", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("processingGenerationId", "processing_generations"),
    ref("eventId", "events"),
    ref("observationId", "observations"),
    text("recordKind"),
    text("fieldKey"),
    text("observationType"),
    text("literalName"),
    text("normalizedName"),
    num("candidateCount"),
    text("status"),
    ts("createdAt"),
    json("resolution"),
  ]),
  table("cardFieldDrops", "card_field_drops", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("processingGenerationId", "processing_generations"),
    text("recordKind"),
    text("kind"),
    text("fieldKey"),
    text("code"),
    text("reason"),
    ts("createdAt"),
  ]),
  table("cardExtractionAttempts", "card_extraction_attempts", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    text("recordKind"),
    text("step"),
    text("gateVersion"),
    text("promptVersion"),
    text("playbookVersion"),
    num("cardSchemaVersion"),
    text("outcome"),
    num("passedFieldCount"),
    num("droppedFieldCount"),
    num("failedFieldCount"),
    json("failureCodes"),
    text("modelId"),
    text("priceTableVersion"),
    num("inputTokens"),
    num("outputTokens"),
    num("costMicroUsd"),
    num("wallTimeMs"),
    ts("createdAt"),
  ]),
  table(
    "cardExtractionQueueStates",
    "card_extraction_queue_states",
    true,
    true,
    [
      text("kind"),
      text("phase"),
      num("cursor"),
      num("dailyDocumentBudget"),
      num("weeklyDocumentBudget"),
      num("weeklyCostBudgetMicroUsd"),
      ts("dayWindowStart"),
      ts("weekWindowStart"),
      num("documentsProcessedToday"),
      num("documentsProcessedThisWeek"),
      num("costMicroUsdThisWeek"),
      num("extractedCount"),
      num("gateFailedCount"),
      num("skippedCount"),
      num("providerFailedCount"),
      num("consecutiveFailures"),
      text("lastErrorCode"),
      text("pauseReason"),
      ts("resumeAt"),
      ts("startedAt"),
      ts("updatedAt"),
    ],
  ),

  // --- Query sessions
  table("recordQuerySessions", "record_query_sessions", true, false, [
    ref("userId", "users"),
    ref("credentialId", "brain_api_keys"),
    ref("membershipId", "space_members"),
    text("authorizationSignature"),
    text("operation"),
    text("consistency"),
    text("normalizedFilter"),
    json("sourceAccountIds"),
    ts("snapshotAt"),
    num("activationEpoch"),
    num("visibilityEpoch"),
    text("lastOccurrenceDate"),
    text("lastOccurrencePrecision"),
    ts("lastOccurrenceInstant"),
    text("lastSortKey"),
    text("lastStableId"),
    json("totals"),
    num("invalidRows"),
    num("ambiguousTimeRows"),
    num("unsupportedValueRows"),
    bool("readOverflow"),
    num("processedRows"),
    ts("createdAt"),
    ts("updatedAt"),
    ts("expiresAt"),
  ]),
  table("recordQuerySpaceState", "record_query_space_state", true, true, [
    num("visibilityEpoch"),
    num("snapshotClock"),
    ts("updatedAt"),
  ]),

  // --- Coverage
  table("coverageWindows", "coverage_windows", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("recordType"),
    ref("entityId", "entities"),
    ts("from"),
    ts("to"),
    text("state"),
    ts("lastEnumeratedAt"),
    ts("lastProcessedAt"),
    num("discoveredCount"),
    num("indexedCount"),
    num("skippedCount"),
  ]),
  table("coverageGaps", "coverage_gaps", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("recordType"),
    ref("entityId", "entities"),
    ts("from"),
    ts("to"),
    text("reason"),
    ts("detectedAt"),
    text("status"),
    ts("resolvedAt"),
  ]),
  table("sourceInventory", "source_inventory", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    text("identityKeyHash"),
    text("relativePath"),
    text("folderPath"),
    text("fileName"),
    num("byteLength"),
    text("contentHash"),
    text("mediaType"),
    ts("modifiedAt"),
    text("duplicateGroupId"),
    bool("contentIndexed"),
    text("exclusionReason"),
    text("exclusionDetail"),
    bool("permissionsRestricted"),
    text("permissionsDetail"),
    ref("firstSeenScanId", "worker_source_scans"),
    ref("lastSeenScanId", "worker_source_scans"),
    ref("missingSinceScanId", "worker_source_scans"),
  ]),

  // --- Embeddings. pgvector and tsvector columns are P2-39g's job (plan
  // section 6); embedding stays jsonb here and the table is not migrated
  // (5.1: vectors are re-derived, content-addressed by inputHash).
  table("embeddingProfiles", "embedding_profiles", false, true, [
    text("fingerprint"),
    text("protocol"),
    text("providerId"),
    text("model"),
    text("modelRevision"),
    num("dimensions"),
    text("normalization"),
    text("preprocessing"),
    ts("createdAt"),
  ]),
  table("spaceEmbeddingStates", "space_embedding_states", true, true, [
    num("eligibilityEpoch"),
    ref("activeEmbeddingGenerationId", "embedding_generations"),
    text("activeFingerprint"),
    ts("activatedAt"),
    json("eligibleCounts"),
    json("coveredCounts"),
    text("targetPolicy"),
    bool("counterDrift"),
    text("counterDriftReason"),
    json("historicalThoughtCounts"),
    ts("lastAuditAt"),
    ts("lastEligibilityChangeAt"),
  ]),
  table("embeddingGenerations", "embedding_generations", true, true, [
    ref("embeddingProfileId", "embedding_profiles"),
    text("fingerprint"),
    text("state"),
    num("eligibilityEpoch"),
    text("manifestHash"),
    num("expectedThoughtCount"),
    num("expectedChunkCount"),
    num("completedThoughtCount"),
    num("completedChunkCount"),
    bool("coverageInvalid"),
    bool("thoughtCoverageInvalid"),
    bool("chunkCoverageInvalid"),
    ts("createdAt"),
    ts("stagedAt"),
    ts("activatedAt"),
    ts("deactivatedAt"),
    text("failureCode"),
    text("failureMessage"),
    ts("failedAt"),
  ]),
  table("embeddingTargets", "embedding_targets", true, true, [
    text("targetKind"),
    text("targetId"),
    text("inputHash"),
    ref("processingGenerationId", "processing_generations"),
    text("state"),
    text("coveredFingerprint"),
    ts("updatedAt"),
  ]),
  table("embeddingBuildJobs", "embedding_build_jobs", true, true, [
    text("fingerprint"),
    ref("embeddingGenerationId", "embedding_generations"),
    text("phase"),
    text("cursor"),
    num("pageIndex"),
    num("scannedCount"),
    num("filledCount"),
    num("retiredCount"),
    json("auditEligibleCounts"),
    json("auditCoveredCounts"),
    num("auditDuplicateTargets"),
    ts("startedAt"),
    ts("updatedAt"),
    text("failureCode"),
    text("failureMessage"),
  ]),
  table("embeddingVectors", "embedding_vectors", true, false, [
    ref("embeddingGenerationId", "embedding_generations"),
    text("embeddingFingerprint"),
    text("targetKind"),
    text("searchScope"),
    ref("thoughtId", "thoughts"),
    ref("chunkId", "brain_chunks"),
    ref("eventId", "events"),
    ref("processingGenerationId", "processing_generations"),
    text("inputHash"),
    json("embedding"),
    text("scopeV2"),
  ]),

  // --- Memory
  table(
    "thoughts",
    "thoughts",
    true,
    true,
    [
      text("content"),
      json("metadata"),
      ref("userId", "users"),
      ts("updatedAt"),
      bool("isCore"),
      ts("validFrom"),
      ts("validTo"),
      text("memoryStatus"),
      ts("supersededAt"),
      ref("supersededBy", "thoughts"),
      json("supersedes"),
      text("changeReason"),
      text("sourceType"),
      text("sourceRef"),
      ts("observedAt"),
      text("batchId"),
      num("confidence"),
    ],
    {
      // Plan 5.1: exported to a cold JSONL audit file, never a column.
      excludedFields: ["embedding"],
    },
  ),
  table("facts", "facts", true, true, [
    ref("userId", "users"),
    ref("subjectEntityId", "entities"),
    text("predicate"),
    json("value"),
    text("statement"),
    text("searchText"),
    text("sourceType"),
    text("sourceRef"),
    ts("observedAt"),
    text("batchId"),
    num("confidence"),
    bool("isCore"),
    ts("validFrom"),
    ts("validTo"),
    text("status"),
    ts("supersededAt"),
    ref("supersededBy", "facts"),
    json("supersedes"),
    text("changeReason"),
    ts("updatedAt"),
  ]),
  table("entities", "entities", true, true, [
    ref("userId", "users"),
    text("key"),
    text("kind"),
    text("canonicalName"),
    text("normalizedName"),
    json("aliases"),
    json("normalizedAliases"),
    ts("updatedAt"),
  ]),

  // --- Workers
  table("workerCleanupState", "worker_cleanup_state", false, true, [
    text("key"),
    num("nextPhase"),
    json("checkpoints"),
  ]),
  table("workerSourceScans", "worker_source_scans", true, false, [
    ref("sourceAccountId", "source_accounts"),
    text("requestId"),
    text("requestDigest"),
    text("watcherId"),
    text("connectorVersion"),
    text("hostAffinity"),
    text("mode"),
    num("inventoryEpoch"),
    num("manifestVersionAtBegin"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    text("state"),
    num("nextPageOrdinal"),
    text("inventoryCursor"),
    bool("inventoryDone"),
    text("lastInventoryRequestId"),
    text("lastInventoryRequestDigest"),
    text("lastInventoryInputCursor"),
    text("lastInventoryOutputCursor"),
    bool("lastInventoryDone"),
    num("pageCount"),
    num("entryCount"),
    num("changedCount"),
    num("gapCount"),
    num("reviewCount"),
    text("sealRequestId"),
    text("sealRequestDigest"),
    num("manifestVersionAtSeal"),
    num("reconcileManifestVersion"),
    text("reconcileCursor"),
    num("nextReconcileOrdinal"),
    bool("reconcileNeedsReview"),
    text("lastReconcileRequestId"),
    text("lastReconcileRequestDigest"),
    json("lastReconcileResult"),
    ts("startedAt"),
    ts("sealedAt"),
    ts("completedAt"),
    text("failureCode"),
    ts("expiresAt"),
    ts("retireAt"),
  ]),
  table("workerScanPages", "worker_scan_pages", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("scanId", "worker_source_scans"),
    num("ordinal"),
    text("requestId"),
    text("requestDigest"),
    ts("redactedAt"),
    num("entryCount"),
    ts("createdAt"),
    ts("retireAt"),
  ]),
  table("workerScanEntries", "worker_scan_entries", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("scanId", "worker_source_scans"),
    ref("scanPageId", "worker_scan_pages"),
    ref("sourceItemId", "source_items"),
    ref("discoveryWorkId", "worker_discovery_work"),
    text("identityKeyHash"),
    text("externalIdHash"),
    text("uriDigest"),
    text("inventoryMetadataDigest"),
    text("processingIdentityDigest"),
    text("contentHash"),
    num("byteLength"),
    text("contentRepresentation"),
    text("binaryParserProfileId"),
    text("binaryMediaType"),
    text("parserFingerprint"),
    text("extractionConfigurationFingerprint"),
    text("extractorFingerprint"),
    text("recordSchemaFingerprint"),
    text("normalizationFingerprint"),
    text("chunkerFingerprint"),
    text("correctionRevision"),
    ts("sourceModifiedAt"),
    num("observationEpoch"),
    num("processingEpoch"),
    text("state"),
    text("issueCode"),
    text("proposedExternalId"),
    text("proposedUri"),
    text("proposedTitle"),
    text("proposedDocType"),
    ts("observedAt"),
    ts("retireAt"),
  ]),
  table("workerDiscoveryWork", "worker_discovery_work", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("scanId", "worker_source_scans"),
    ref("scanEntryId", "worker_scan_entries"),
    num("observationEpoch"),
    num("processingEpoch"),
    num("expectedDesiredProcessingEpoch"),
    text("state"),
    text("contentHash"),
    num("byteLength"),
    ts("capturedAt"),
    ts("sourceModifiedAt"),
    text("mediaType"),
    text("profileId"),
    text("contentRepresentation"),
    text("parserFingerprint"),
    text("extractionConfigurationFingerprint"),
    text("correctionRevision"),
    text("extractionFingerprint"),
    text("extractorFingerprint"),
    text("recordSchemaFingerprint"),
    text("normalizationFingerprint"),
    text("chunkerFingerprint"),
    text("title"),
    text("docType"),
    text("uri"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    num("attempts"),
    num("leaseEpoch"),
    text("leaseToken"),
    ref("leaseOwnerCredentialId", "brain_api_keys"),
    ts("leaseExpiresAt"),
    ts("nextAttemptAt"),
    text("failureCode"),
    bool("retryable"),
    text("ingestRequestId"),
    ref("ingestJobId", "ingest_jobs"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("processingGenerationId", "processing_generations"),
    ts("createdAt"),
    ts("retireAt"),
  ]),
  table("sourceAliasDigests", "source_alias_digests", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    text("kind"),
    text("digest"),
    ts("firstSeenAt"),
    ts("lastSeenAt"),
  ]),
  table(
    "workerProtocolRateLimits",
    "worker_protocol_rate_limits",
    false,
    false,
    [
      ref("credentialId", "brain_api_keys"),
      ref("sourceAccountId", "source_accounts"),
      ts("windowStartedAt"),
      num("count"),
    ],
  ),
  table("workerReservationReceipts", "worker_reservation_receipts", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("kind"),
    text("requestId"),
    text("requestDigest"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    num("targetCount"),
    ts("createdAt"),
    ts("expiresAt"),
    ts("invalidatedAt"),
    ts("retireAt"),
  ]),
  table("workerReservationTargets", "worker_reservation_targets", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("receiptId", "worker_reservation_receipts"),
    num("ordinal"),
    ref("discoveryWorkId", "worker_discovery_work"),
    ref("ingestJobId", "ingest_jobs"),
    num("leaseEpoch"),
    text("leaseToken"),
    ts("leaseExpiresAt"),
  ]),
  table("workerOperationReceipts", "worker_operation_receipts", true, true, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("discoveryWorkId", "worker_discovery_work"),
    text("operation"),
    text("phase"),
    text("requestId"),
    text("requestDigest"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    num("leaseEpoch"),
    text("leaseTokenHash"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("processingGenerationId", "processing_generations"),
    ref("ingestJobId", "ingest_jobs"),
    num("desiredProcessingEpoch"),
    text("resultState"),
    ts("resultLeaseExpiresAt"),
    ts("resultActivatedAt"),
    ref("resultPreviousGenerationId", "processing_generations"),
    num("resultActualPageCount"),
    num("resultActualEvidenceSpanCount"),
    num("resultActualDocumentCount"),
    num("resultActualChunkCount"),
    bool("resultRetryable"),
    ts("resultNextAttemptAt"),
    text("resultFailureCode"),
    ts("resultFailureAt"),
    ts("createdAt"),
    ts("retireAt"),
  ]),
  table(
    "workerBinaryOperationReceipts",
    "worker_binary_operation_receipts",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("sourceItemId", "source_items"),
      ref("discoveryWorkId", "worker_discovery_work"),
      text("operation"),
      text("phase"),
      text("requestId"),
      text("requestDigest"),
      ref("actorUserId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      num("leaseEpoch"),
      text("leaseTokenHash"),
      ts("leaseExpiresAtAtRequest"),
      ref("sourceRevisionId", "brain_source_revisions"),
      ref("parserArtifactId", "source_parser_artifacts"),
      ref("sourceTextVersionId", "source_text_versions"),
      ref("processingGenerationId", "processing_generations"),
      ref("ingestJobId", "ingest_jobs"),
      num("desiredProcessingEpoch"),
      text("archiveSetDigest"),
      ref(
        "originalProviderReferenceId",
        "source_provider_original_references",
      ),
      num("originalProviderBindingEpoch"),
      ref("stageId", "worker_parsed_stages"),
      text("stagePhase"),
      num("stageOrdinal"),
      num("stageAcceptedCount"),
      text("resultState"),
      ts("resultLeaseExpiresAt"),
      ts("resultNextAttemptAt"),
      bool("resultRetryable"),
      text("resultFailureCode"),
      ts("resultFailureAt"),
      text("resultStagePhase"),
      ts("resultActivatedAt"),
      ref("resultPreviousGenerationId", "processing_generations"),
      ref("payloadManifestId", "processing_generation_payload_manifests"),
      ts("createdAt"),
      ts("retireAt"),
    ],
  ),
  table(
    "workerProcessingAssessments",
    "worker_processing_assessments",
    true,
    false,
    [
      ref("sourceAccountId", "source_accounts"),
      ref("scanId", "worker_source_scans"),
      text("requestId"),
      text("requestDigest"),
      ref("actorUserId", "users"),
      ref("actorCredentialId", "brain_api_keys"),
      num("inventoryEpoch"),
      num("completedInventoryEpoch"),
      num("manifestVersion"),
      num("assessmentEpoch"),
      ts("coverageInvalidatedAt"),
      ts("lastEnumeratedAt"),
      ts("lastProcessedAtAtStart"),
      ts("scanCompletedAt"),
      text("scanStateAtStart"),
      num("scanEntryCount"),
      num("scanChangedCount"),
      num("scanGapCount"),
      num("scanReviewCount"),
      text("state"),
      text("staleReason"),
      text("phase"),
      text("cursor"),
      num("nextOrdinal"),
      json("counts"),
      num("accountedScanEntries"),
      num("queuedScanEntries"),
      num("gapScanEntries"),
      num("reviewScanEntries"),
      num("ignoredScanEntries"),
      num("unchangedScanEntries"),
      text("lastPageRequestId"),
      text("lastPageRequestDigest"),
      text("lastPageInputPhase"),
      num("lastPageOrdinal"),
      json("lastPageResult"),
      ts("startedAt"),
      ts("updatedAt"),
      ts("expiresAt"),
      ts("completedAt"),
      ts("lastProcessedAtAtCompletion"),
      ts("retireAt"),
    ],
  ),
  table("workerWatcherStates", "worker_watcher_states", true, true, [
    ref("sourceAccountId", "source_accounts"),
    text("watcherId"),
    text("state"),
    text("connectorVersion"),
    ref("actorUserId", "users"),
    ref("actorCredentialId", "brain_api_keys"),
    ts("lastSeenAt"),
    ts("nextExpectedAt"),
    ts("sweepAfter"),
    ts("createdAt"),
    ts("updatedAt"),
  ]),
  table(
    "workerOperationalIncidents",
    "worker_operational_incidents",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      text("watcherId"),
      text("kind"),
      text("state"),
      ts("openedAt"),
      ts("observedAt"),
      ts("resolvedAt"),
    ],
  ),
  table(
    "workerWatcherResetReceipts",
    "worker_watcher_reset_receipts",
    true,
    true,
    [
      ref("sourceAccountId", "source_accounts"),
      text("requestId"),
      text("requestDigest"),
      text("expectedWatcherId"),
      text("nextWatcherId"),
      ref("actorUserId", "users"),
      ts("changedAt"),
    ],
  ),
  table("workerParsedStages", "worker_parsed_stages", true, false, [
    ref("sourceAccountId", "source_accounts"),
    ref("sourceItemId", "source_items"),
    ref("discoveryWorkId", "worker_discovery_work"),
    ref("ingestJobId", "ingest_jobs"),
    ref("processingGenerationId", "processing_generations"),
    ref("sourceRevisionId", "brain_source_revisions"),
    ref("sourceTextVersionId", "source_text_versions"),
    ref("parserArtifactId", "source_parser_artifacts"),
    text("archiveSetDigest"),
    text("normalizedBundleDigest"),
    text("mappingManifestHash"),
    text("phase"),
    num("nextOrdinal"),
    num("expectedPageCount"),
    num("expectedEvidenceSpanCount"),
    num("expectedDocumentCount"),
    num("expectedChunkCount"),
    num("acceptedPageCount"),
    num("acceptedEvidenceSpanCount"),
    num("acceptedDocumentCount"),
    num("acceptedChunkCount"),
    json("pageIds"),
    json("evidenceSpanIds"),
    json("documentIds"),
    json("chunkIds"),
    num("pageBytes"),
    num("evidenceBytes"),
    num("documentBytes"),
    num("chunkBytes"),
    ref("payloadManifestId", "processing_generation_payload_manifests"),
    ts("createdAt"),
    ts("updatedAt"),
    ts("retireAt"),
  ]),
];

export const RETIRED_CONVEX_TABLES = [
  "lists",
  "listItems",
  "reports",
  "insights",
];

/** Convex tables neither migrated nor given a `kith` target by the plan:
 * session and verifier state a fresh `kith.sessions` design (P2-39c) replaces
 * outright. Exporting them is harmless (export is table-agnostic); the
 * transform simply has no target for them. */
export const NO_TARGET_CONVEX_TABLES = [
  "authSessions",
  "authRefreshTokens",
  "authVerificationCodes",
  "authVerifiers",
  "authRateLimits",
];

export function findTable(convexTable: string): TableSpec | undefined {
  return TABLES.find((t) => t.convexTable === convexTable);
}
