import { v } from "convex/values";

export const workerScanModeValidator = v.union(
  v.literal("normal"),
  v.literal("identity_recovery"),
);

export const workerScanStateValidator = v.union(
  v.literal("open"),
  v.literal("sealed"),
  v.literal("reconciling"),
  v.literal("enumerated"),
  v.literal("needs_review"),
  v.literal("failed"),
);

export const workerGapCodeValidator = v.union(
  v.literal("empty"),
  v.literal("enumeration_interrupted"),
  v.literal("oversized"),
  v.literal("permission_denied"),
  v.literal("unreadable"),
  v.literal("unstable"),
  v.literal("unsupported"),
);

export const workerScanEntryStateValidator = v.union(
  v.literal("unchanged"),
  v.literal("queued"),
  v.literal("gap"),
  v.literal("ignored_forgotten"),
  v.literal("needs_review"),
);

export const workerDiscoveryStateValidator = v.union(
  v.literal("queued"),
  v.literal("leased"),
  v.literal("admitted"),
  v.literal("needs_review"),
  v.literal("failed"),
  v.literal("obsolete"),
);

export const workerAssessmentStateValidator = v.union(
  v.literal("running"),
  v.literal("complete"),
  v.literal("incomplete"),
  v.literal("stale"),
);

export const workerAssessmentPhaseValidator = v.union(
  v.literal("items"),
  v.literal("unresolved_entries"),
  v.literal("done"),
);

export const workerAssessmentStaleReasonValidator = v.union(
  v.literal("source_changed"),
  v.literal("detail_unavailable"),
  v.literal("expired"),
);

export const workerAssessmentCountsValidator = v.object({
  items: v.object({
    ready: v.number(),
    pending: v.number(),
    failed: v.number(),
    needsReview: v.number(),
    explicitGap: v.number(),
    unavailable: v.number(),
    ignoredForgotten: v.number(),
  }),
  unresolvedEntries: v.object({
    needsReview: v.number(),
    ignoredForgotten: v.number(),
  }),
});

export const workerProcessingAssessmentFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  scanId: v.id("workerSourceScans"),
  requestId: v.string(),
  requestDigest: v.string(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  inventoryEpoch: v.number(),
  completedInventoryEpoch: v.number(),
  manifestVersion: v.number(),
  assessmentEpoch: v.number(),
  coverageInvalidatedAt: v.number(),
  lastEnumeratedAt: v.number(),
  lastProcessedAtAtStart: v.number(),
  scanCompletedAt: v.number(),
  scanStateAtStart: v.union(v.literal("enumerated"), v.literal("needs_review")),
  scanEntryCount: v.number(),
  scanChangedCount: v.number(),
  scanGapCount: v.number(),
  scanReviewCount: v.number(),
  state: workerAssessmentStateValidator,
  staleReason: v.optional(workerAssessmentStaleReasonValidator),
  phase: workerAssessmentPhaseValidator,
  cursor: v.optional(v.string()),
  nextOrdinal: v.number(),
  counts: workerAssessmentCountsValidator,
  accountedScanEntries: v.number(),
  queuedScanEntries: v.number(),
  gapScanEntries: v.number(),
  reviewScanEntries: v.number(),
  ignoredScanEntries: v.number(),
  unchangedScanEntries: v.number(),
  lastPageRequestId: v.optional(v.string()),
  lastPageRequestDigest: v.optional(v.string()),
  lastPageInputPhase: v.optional(workerAssessmentPhaseValidator),
  lastPageOrdinal: v.optional(v.number()),
  lastPageResult: v.optional(
    v.object({
      state: workerAssessmentStateValidator,
      phase: workerAssessmentPhaseValidator,
      ordinal: v.number(),
      inspected: v.number(),
      nextOrdinal: v.number(),
      counts: v.optional(workerAssessmentCountsValidator),
      completedAt: v.optional(v.number()),
      staleReason: v.optional(workerAssessmentStaleReasonValidator),
    }),
  ),
  startedAt: v.number(),
  updatedAt: v.number(),
  expiresAt: v.number(),
  completedAt: v.optional(v.number()),
  lastProcessedAtAtCompletion: v.optional(v.number()),
  retireAt: v.number(),
};

export const workerSourceScanFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  requestId: v.string(),
  requestDigest: v.string(),
  watcherId: v.string(),
  connectorVersion: v.string(),
  hostAffinity: v.optional(v.string()),
  mode: workerScanModeValidator,
  inventoryEpoch: v.number(),
  manifestVersionAtBegin: v.number(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  state: workerScanStateValidator,
  nextPageOrdinal: v.number(),
  inventoryCursor: v.optional(v.string()),
  inventoryDone: v.boolean(),
  lastInventoryRequestId: v.optional(v.string()),
  lastInventoryRequestDigest: v.optional(v.string()),
  lastInventoryInputCursor: v.optional(v.string()),
  lastInventoryOutputCursor: v.optional(v.string()),
  lastInventoryDone: v.optional(v.boolean()),
  pageCount: v.number(),
  entryCount: v.number(),
  changedCount: v.number(),
  gapCount: v.number(),
  reviewCount: v.number(),
  sealRequestId: v.optional(v.string()),
  sealRequestDigest: v.optional(v.string()),
  manifestVersionAtSeal: v.optional(v.number()),
  reconcileManifestVersion: v.optional(v.number()),
  reconcileCursor: v.optional(v.string()),
  nextReconcileOrdinal: v.number(),
  reconcileNeedsReview: v.optional(v.boolean()),
  lastReconcileRequestId: v.optional(v.string()),
  lastReconcileRequestDigest: v.optional(v.string()),
  lastReconcileResult: v.optional(
    v.object({
      state: v.union(
        v.literal("reconciling"),
        v.literal("enumerated"),
        v.literal("needs_review"),
      ),
      inspected: v.number(),
      unavailable: v.number(),
      done: v.boolean(),
    }),
  ),
  startedAt: v.number(),
  sealedAt: v.optional(v.number()),
  completedAt: v.optional(v.number()),
  failureCode: v.optional(workerGapCodeValidator),
  expiresAt: v.number(),
  retireAt: v.number(),
};

export const workerScanPageFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  scanId: v.id("workerSourceScans"),
  ordinal: v.number(),
  requestId: v.string(),
  requestDigest: v.optional(v.string()),
  redactedAt: v.optional(v.number()),
  entryCount: v.number(),
  createdAt: v.number(),
  retireAt: v.number(),
};

export const workerScanEntryFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  scanId: v.id("workerSourceScans"),
  scanPageId: v.id("workerScanPages"),
  sourceItemId: v.optional(v.id("sourceItems")),
  discoveryWorkId: v.optional(v.id("workerDiscoveryWork")),
  identityKeyHash: v.string(),
  externalIdHash: v.optional(v.string()),
  uriDigest: v.string(),
  inventoryMetadataDigest: v.string(),
  processingIdentityDigest: v.optional(v.string()),
  contentHash: v.optional(v.string()),
  byteLength: v.optional(v.number()),
  contentRepresentation: v.optional(
    v.union(v.literal("inline_utf8_v1"), v.literal("archived_binary_v1")),
  ),
  binaryParserProfileId: v.optional(v.literal("pdf_docqa_v1")),
  binaryMediaType: v.optional(v.literal("application/pdf")),
  parserFingerprint: v.optional(v.string()),
  extractionConfigurationFingerprint: v.optional(v.string()),
  extractorFingerprint: v.optional(v.string()),
  recordSchemaFingerprint: v.optional(v.string()),
  normalizationFingerprint: v.optional(v.string()),
  chunkerFingerprint: v.optional(v.string()),
  correctionRevision: v.optional(v.string()),
  sourceModifiedAt: v.number(),
  observationEpoch: v.optional(v.number()),
  processingEpoch: v.optional(v.number()),
  state: workerScanEntryStateValidator,
  issueCode: v.optional(v.string()),
  proposedExternalId: v.optional(v.string()),
  proposedUri: v.optional(v.string()),
  proposedTitle: v.optional(v.string()),
  proposedDocType: v.optional(v.string()),
  observedAt: v.number(),
  retireAt: v.number(),
};

export const workerDiscoveryWorkFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  scanId: v.id("workerSourceScans"),
  scanEntryId: v.id("workerScanEntries"),
  observationEpoch: v.number(),
  processingEpoch: v.number(),
  expectedDesiredProcessingEpoch: v.optional(v.number()),
  state: workerDiscoveryStateValidator,
  contentHash: v.string(),
  byteLength: v.number(),
  capturedAt: v.number(),
  sourceModifiedAt: v.number(),
  mediaType: v.string(),
  profileId: v.string(),
  contentRepresentation: v.optional(
    v.union(v.literal("inline_utf8_v1"), v.literal("archived_binary_v1")),
  ),
  parserFingerprint: v.optional(v.string()),
  extractionConfigurationFingerprint: v.optional(v.string()),
  correctionRevision: v.optional(v.string()),
  extractionFingerprint: v.string(),
  extractorFingerprint: v.string(),
  recordSchemaFingerprint: v.string(),
  normalizationFingerprint: v.string(),
  chunkerFingerprint: v.string(),
  title: v.optional(v.string()),
  docType: v.optional(v.string()),
  uri: v.string(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  attempts: v.number(),
  leaseEpoch: v.number(),
  leaseToken: v.optional(v.string()),
  leaseOwnerCredentialId: v.optional(v.id("apiKeys")),
  leaseExpiresAt: v.optional(v.number()),
  nextAttemptAt: v.optional(v.number()),
  failureCode: v.optional(v.string()),
  retryable: v.optional(v.boolean()),
  ingestRequestId: v.optional(v.string()),
  ingestJobId: v.optional(v.id("ingestJobs")),
  sourceRevisionId: v.optional(v.id("sourceRevisions")),
  processingGenerationId: v.optional(v.id("processingGenerations")),
  createdAt: v.number(),
  retireAt: v.number(),
};

export const workerBinaryOperationReceiptFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  discoveryWorkId: v.id("workerDiscoveryWork"),
  operation: v.union(
    v.literal("discovery_admit_archived"),
    v.literal("job_renew_parsed"),
    v.literal("job_fail_parsed"),
    v.literal("job_stage_parsed_begin"),
    v.literal("job_stage_parsed_batch"),
    v.literal("job_stage_parsed_seal"),
    v.literal("job_activate_parsed"),
  ),
  phase: v.union(v.literal("pending"), v.literal("completed")),
  requestId: v.string(),
  requestDigest: v.string(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  leaseEpoch: v.number(),
  leaseTokenHash: v.string(),
  leaseExpiresAtAtRequest: v.optional(v.number()),
  sourceRevisionId: v.optional(v.id("sourceRevisions")),
  parserArtifactId: v.optional(v.id("sourceParserArtifacts")),
  sourceTextVersionId: v.optional(v.id("sourceTextVersions")),
  processingGenerationId: v.optional(v.id("processingGenerations")),
  ingestJobId: v.optional(v.id("ingestJobs")),
  desiredProcessingEpoch: v.optional(v.number()),
  archiveSetDigest: v.optional(v.string()),
  stageId: v.optional(v.id("workerParsedStages")),
  stagePhase: v.optional(
    v.union(
      v.literal("pages"),
      v.literal("evidence"),
      v.literal("documents"),
      v.literal("chunks"),
      v.literal("seal"),
      v.literal("staged"),
    ),
  ),
  stageOrdinal: v.optional(v.number()),
  stageAcceptedCount: v.optional(v.number()),
  resultState: v.optional(
    v.union(
      v.literal("processing"),
      v.literal("staged"),
      v.literal("ready"),
      v.literal("failed"),
      v.literal("needs_review"),
      v.literal("obsolete_generation"),
    ),
  ),
  resultLeaseExpiresAt: v.optional(v.number()),
  resultNextAttemptAt: v.optional(v.number()),
  resultRetryable: v.optional(v.boolean()),
  resultFailureCode: v.optional(v.string()),
  resultFailureAt: v.optional(v.number()),
  resultStagePhase: v.optional(
    v.union(
      v.literal("pages"),
      v.literal("evidence"),
      v.literal("documents"),
      v.literal("chunks"),
      v.literal("seal"),
      v.literal("staged"),
    ),
  ),
  resultActivatedAt: v.optional(v.number()),
  resultPreviousGenerationId: v.optional(v.id("processingGenerations")),
  payloadManifestId: v.optional(v.id("processingGenerationPayloadManifests")),
  createdAt: v.number(),
  retireAt: v.number(),
};

export const workerReservationReceiptFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  kind: v.union(
    v.literal("discovery"),
    v.literal("archived_discovery"),
    v.literal("processing"),
    v.literal("parsed_processing"),
  ),
  requestId: v.string(),
  requestDigest: v.string(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  targetCount: v.number(),
  createdAt: v.number(),
  expiresAt: v.number(),
  invalidatedAt: v.optional(v.number()),
  retireAt: v.number(),
};

export const workerParsedStageFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  discoveryWorkId: v.id("workerDiscoveryWork"),
  ingestJobId: v.id("ingestJobs"),
  processingGenerationId: v.id("processingGenerations"),
  sourceRevisionId: v.id("sourceRevisions"),
  sourceTextVersionId: v.id("sourceTextVersions"),
  parserArtifactId: v.id("sourceParserArtifacts"),
  archiveSetDigest: v.string(),
  normalizedBundleDigest: v.string(),
  mappingManifestHash: v.string(),
  phase: v.union(
    v.literal("pages"),
    v.literal("evidence"),
    v.literal("documents"),
    v.literal("chunks"),
    v.literal("seal"),
    v.literal("staged"),
  ),
  nextOrdinal: v.number(),
  expectedPageCount: v.number(),
  expectedEvidenceSpanCount: v.number(),
  expectedDocumentCount: v.number(),
  expectedChunkCount: v.number(),
  acceptedPageCount: v.number(),
  acceptedEvidenceSpanCount: v.number(),
  acceptedDocumentCount: v.number(),
  acceptedChunkCount: v.number(),
  pageIds: v.array(v.id("sourcePages")),
  evidenceSpanIds: v.array(v.id("evidenceSpans")),
  documentIds: v.array(v.id("documents")),
  chunkIds: v.array(v.id("chunks")),
  pageBytes: v.number(),
  evidenceBytes: v.number(),
  documentBytes: v.number(),
  chunkBytes: v.number(),
  payloadManifestId: v.optional(v.id("processingGenerationPayloadManifests")),
  createdAt: v.number(),
  updatedAt: v.number(),
  retireAt: v.number(),
};

export const workerReservationTargetFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  receiptId: v.id("workerReservationReceipts"),
  ordinal: v.number(),
  discoveryWorkId: v.optional(v.id("workerDiscoveryWork")),
  ingestJobId: v.optional(v.id("ingestJobs")),
  leaseEpoch: v.number(),
  leaseToken: v.string(),
  leaseExpiresAt: v.number(),
};

export const workerOperationReceiptFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  discoveryWorkId: v.id("workerDiscoveryWork"),
  operation: v.union(
    v.literal("discovery_admit_utf8"),
    v.literal("job_renew"),
    v.literal("job_stage_utf8"),
    v.literal("job_activate"),
    v.literal("job_fail"),
  ),
  phase: v.optional(v.union(v.literal("pending"), v.literal("completed"))),
  requestId: v.string(),
  requestDigest: v.string(),
  actorUserId: v.id("users"),
  actorCredentialId: v.id("apiKeys"),
  leaseEpoch: v.number(),
  leaseTokenHash: v.string(),
  sourceRevisionId: v.id("sourceRevisions"),
  processingGenerationId: v.id("processingGenerations"),
  ingestJobId: v.id("ingestJobs"),
  desiredProcessingEpoch: v.number(),
  resultState: v.optional(
    v.union(
      v.literal("processing"),
      v.literal("staged"),
      v.literal("ready"),
      v.literal("failed"),
      v.literal("needs_review"),
      v.literal("obsolete_generation"),
    ),
  ),
  resultLeaseExpiresAt: v.optional(v.number()),
  resultActivatedAt: v.optional(v.number()),
  resultPreviousGenerationId: v.optional(v.id("processingGenerations")),
  resultActualPageCount: v.optional(v.number()),
  resultActualEvidenceSpanCount: v.optional(v.number()),
  resultActualDocumentCount: v.optional(v.number()),
  resultActualChunkCount: v.optional(v.number()),
  resultRetryable: v.optional(v.boolean()),
  resultNextAttemptAt: v.optional(v.number()),
  resultFailureCode: v.optional(v.string()),
  resultFailureAt: v.optional(v.number()),
  createdAt: v.number(),
  retireAt: v.number(),
};

export const sourceAliasDigestFields = {
  spaceId: v.id("spaces"),
  sourceAccountId: v.id("sourceAccounts"),
  sourceItemId: v.id("sourceItems"),
  kind: v.literal("uri"),
  digest: v.string(),
  firstSeenAt: v.number(),
  lastSeenAt: v.number(),
};

export const workerProtocolRateLimitFields = {
  credentialId: v.id("apiKeys"),
  sourceAccountId: v.id("sourceAccounts"),
  windowStartedAt: v.number(),
  count: v.number(),
};
